sshd:
  listen-port: 32222
  listen-interface: 0.0.0.0
  forwarding:
    start-port: 31000
    end-port:   32000


spring:
  cloud:
    kubernetes:
      config:
        enabled: true
      reload:
        enabled: false
