sshd:
  listen-port: 32222
  listen-interface: 0.0.0.0
  forwarding:
    min-port: 31000
    max-port:   33000
  idle-timeout-ms: 60000
  print-stats-interval: 600000



spring:
  cloud:
    kubernetes:
      config:
        enabled: true
      reload:
        enabled: false
      discovery:
        catalog-services-watch:
          enabled: false