portto:
  servers-list:
    - 192.168.1.113:32222
    - unreachable-porto.vyukov.ru:32222
    - portto.vyukov.ru:32222
  #private-key-path: #{null} #default
  #user-name: portto #default
  #password: qwerty #default


---
spring:
  profiles:
    active: ci

---
spring:
  profiles:
    active: production
