apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portto-server.name" . }}
  labels:
    app: {{ template "portto-server.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yml: |-
    sshd:
{{ toYaml .Values.sshd | indent 6 }}

