# Default values for portto-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:  docker.io/portto/portto-server
  tag: 0.1
  pullPolicy: IfNotPresent



#typically kubernetes allow  nodePorts 30000–32767
sshd:
  port: 32222
  forwarding:
    startPort: 32223
    endPort:   32300


resources:
   limits:
    cpu: 1
    memory: 256Mi
   requests:
    cpu: 0.2
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
